language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t cumulus96/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cumulus96/react-test npm run test 

after_success:
  - docker build -t cumulus96/multi-client ./client
  - docker build -t cumulus96/multi-nginx ./nginx
  - docker build -t cumulus96/multi-server ./server
  - docker build -t cumulus96/multi-worker ./worker 

# Log into Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take images and push to docker hub
  - docker push cumulus96/multi-client
  - docker push cumulus96/multi-nginx
  - docker push cumulus96/multi-server
  - docker push cumulus96/multi-worker

#
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-424346776618"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY